dashboard/urls.py
from django.urls import path
from .views import index, members_detail, privacy, terms

app_name = 'dashboard'
urlpatterns = [
  path('', index, name='index'),
  path('members/<str:pk>', members_detail, name='members-detail'),
  path('privacy-policy', privacy, name='privacy'),
  path('terms-and-conditions', terms, name='terms'),
]

events/urls.py
from django.urls import path
from .views import index, event_detail, subscribe, create_event_view

app_name = 'events'
urlpatterns = [
  path('', index, name='index'),
  path('<str:slug>', event_detail, name='events-detail'),
  path('subscribe/', subscribe, name='subscribe'),
  path('create-event/', create_event_view, name='create-event'),
]

oracleku/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('events/', include('events.urls')),
    path('users/', include('signup.urls')),
    path('', include('dashboard.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signup/urls.py
from django.urls import path
from .views import index, signin

app_name = 'signup'
urlpatterns = [
  path('signup', index, name='index'),
  path('signin', signin, name='login'),
]

templates/partials/_footer.html
<div class="bg-secondary text-white">
<div class="container"> 
  <div class="subscribe-form">
    <form action="{% url 'events:subscribe' %}" method="POST" class="py-4">
      {% csrf_token %}
      <h4>Subscribe To Our Newsletter</h4>
      <p>Join the community to get latest events when uploaded to the site.</p>
      <div class="form-input">
        <input type="text" name="email" id="email" class="form-control" placeholder="someone@example.com">
        <button type="submit" class="btn btn-danger btn-inline">Subscribe</button>
      </div>
    </form>
  </div>
  <hr>
  <div class="row py-2">
    <div class="col-md-6">
      <ul class="social-1">
        <li class="nav-item"><a href="#!" class="nav-link text-white">About</a></li>
        <li class="nav-item"><a href="#!" class="nav-link text-white">Contact</a></li>
        <li class="nav-item"><a href="https://www.oracle.com/ke/education/" target="_blank" class="nav-link text-white">Oracle Courses</a></li>
        <li class="nav-item"><a href="#!" class="nav-link text-white">Blog</a></li>
      </ul>
    </div>
    <div class="col-md-6">
      <ul class="social-2">
        <li class="nav-item"><a href="https://twitter.com/oracle_ku" target="_blank" class="nav-link text-white">Twitter</a></li>
        <li class="nav-item"><a href="#!" class="nav-link text-white">Facebook</a></li>
        <li class="nav-item"><a href="#!" class="nav-link text-white">Linkedin</a></li>
        <li class="nav-item"><a href="#!" class="nav-link text-white">Instagram</a></li>
      </ul>
    </div>
  </div>
</div>
</div>
<div class="py-4 bg-dark text-center">
  <p class="text-white"> Kenyatta University Oracle Club &copy; <span id="year"></span> <a href="{% url 'dashboard:privacy' %}">Privacy</a> | <a href="{% url 'dashboard:terms' %}">Terms</a></p>
</div>

<script>
  let year = new Date().getFullYear();
  document.getElementById('year').innerHTML = year;
</script>

templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-sm navbar-light bg-light py-4">
  <div class="container">
    <a href="{% url 'dashboard:index' %}" class="navbar-brand"><img src="{% static 'images/ku-oracle-logo.png' %}" class="club-logo" alt="Ku Oracle Club"></a>

    <button 
    type="button"
    data-toggle="collapse"
    data-target="#navbarMain"
    aria-controls="navbarMain"
    aria-label="Toggle navigation"
    aria-expanded="false" class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a href="{% url 'events:index' %}" class="nav-link text-danger ml-3">Events</a></li>
        <li class="nav-item"><a href="https://www.oracle.com/ke/education/" target="_blank" class="nav-link text-danger ml-3">Find Courses</a></li>
        <li class="nav-item"><button class="btn btn-sm border-success"><a href="{% url 'signup:index' %}" class="nav-link text-success">Become a Member</a></button></li>
        {% if request.user.is_authenticated %}
          {% if request.user.is_staff %}
          <li class="nav-item"><a href="{% url 'events:create-event' %}" class="nav-link text-success">Create</a></li>
          {% endif %}
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}} text-center">{{message}}</div>
  {% endfor %}
{% endif %}